package com.northsignalstudio.myram.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4A6CF7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_surface = Color(0xFFF3F5F8)
val md_theme_light_onSurface = Color(0xFF1C1C1E)
val md_theme_light_outline = Color(0xFFAEB6C2)
val md_theme_light_editorEntryBackground = Color(0xFFF5F6F9)

val md_theme_dark_primary = Color(0xFF88A1FF)
val md_theme_dark_onPrimary = Color(0xFF1C1C1E)
val md_theme_dark_surface = Color(0xFF18191B)
val md_theme_dark_onSurface = Color(0xFFECECEC)
val md_theme_dark_outline = Color(0xFF54565C)
val md_theme_dark_editorEntryBackground = Color(0xFF2C2C2E)
val md_theme_dark_toolbarBackground = Color(0xFF2C2C2E)

val warm_paper_primary = Color(0xFFC76D00)
val warm_paper_onPrimary = Color(0xFFFFFFFF)
val warm_paper_background = Color(0xFFF0E5D3)
val warm_paper_surface = Color(0xFFFFFAF1)
val warm_paper_surfaceVariant = Color(0xFFFAEFDB)
val warm_paper_primaryContainer = Color(0xFFECDABB)
val warm_paper_onSurface = Color(0xFF1C1C1E)
val warm_paper_onSurfaceVariant = Color(0xFF5B4B38)
val warm_paper_outline = Color(0xFF885B27)
val warm_paper_toolbar = Color(0xFFFFFAF1)

val warm_paper_dark_primary = Color(0xFFEB9F42)
val warm_paper_dark_onPrimary = Color(0xFF1C1C1E)
val warm_paper_dark_background = Color(0xFF221D17)
val warm_paper_dark_surface = Color(0xFF2E271F)
val warm_paper_dark_surfaceVariant = Color(0xFF392F24)
val warm_paper_dark_primaryContainer = Color(0xFF493A2B)
val warm_paper_dark_onSurface = Color(0xFFF6E9D6)
val warm_paper_dark_onSurfaceVariant = Color(0xFFE0C6A8)
val warm_paper_dark_outline = Color(0xFFC99B64)
val warm_paper_dark_toolbar = Color(0xFF392F24)
